<a href="https://colab.research.google.com/github/heydi98-hl/datamining/blob/main/Ejercicio3AgrupacionParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/heydi98-hl/datamining/refs/heads/main/Archivo/clave_E_agrupacion.csv")

df.head()

,registro_id,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
0,E-R0096,39,986,7.83,99.00,8.08,2,24
1,E-R0092,41,905,5.52,82.98,8.07,2,23
2,E-R0079,34,1109,7.17,65.25,8.46,0,13
3,E-R0019,32,618,2.57,25.75,5.09,12,21
4,E-R0174,49,1592,8.08,172.04,6.55,0,28

In [4]:

df.shape

(246, 8)

In [5]:
df.describe()

,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
count,246.000000,246.000000,246.000000,246.000000,245.00000,246.000000,246.000000
mean,38.028455,1029.247967,5.260488,82.054309,6.95849,2.455285,17.634146
std,10.302130,423.124191,3.012360,47.307920,1.85331,2.037413,12.897567
min,18.000000,370.000000,0.000000,5.000000,2.04000,0.000000,1.000000
25%,30.000000,707.500000,2.915000,50.005000,5.47000,1.000000,8.000000
50%,38.500000,934.500000,5.365000,76.185000,7.18000,2.000000,15.000000
75%,46.000000,1261.250000,7.467500,106.317500,8.47000,4.000000,24.000000
max,62.000000,2900.000000,11.400000,260.000000,10.00000,12.000000,52.000000

In [6]:
df.isnull().sum()

registro_id         0
edad                0
ingresos            0
frecuencia_uso      0
gasto_promedio      0
satisfaccion        1
reclamos            0
antiguedad_meses    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   registro_id       246 non-null    object
 1   edad              246 non-null    int64
 2   ingresos          246 non-null    int64
 3   frecuencia_uso    246 non-null    float64
 4   gasto_promedio    246 non-null    float64
 5   satisfaccion      245 non-null    float64
 6   reclamos          246 non-null    int64
 7   antiguedad_meses  246 non-null    int64
dtypes: float64(3), int64(4), object(1)
memory usage: 15.5+ KB

In [8]:
df.isnull().sum()

registro_id         0
edad                0
ingresos            0
frecuencia_uso      0
gasto_promedio      0
satisfaccion        1
reclamos            0
antiguedad_meses    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
count,246.000000,246.000000,246.000000,246.000000,245.00000,246.000000,246.000000
mean,38.028455,1029.247967,5.260488,82.054309,6.95849,2.455285,17.634146
std,10.302130,423.124191,3.012360,47.307920,1.85331,2.037413,12.897567
min,18.000000,370.000000,0.000000,5.000000,2.04000,0.000000,1.000000
25%,30.000000,707.500000,2.915000,50.005000,5.47000,1.000000,8.000000
50%,38.500000,934.500000,5.365000,76.185000,7.18000,2.000000,15.000000
75%,46.000000,1261.250000,7.467500,106.317500,8.47000,4.000000,24.000000
max,62.000000,2900.000000,11.400000,260.000000,10.00000,12.000000,52.000000